http:
  routers:
    rpi:
      entryPoints: # If not specified, HTTP routers will accept requests from all defined entry points
        - "https"
        - "http"
      rule: "Host (`prodanov.org`)"
      tls: true
      service: rpi
  services:
    rpi:
      loadBalancer:
        servers:
          - url: "https://10.1.0.9:443"
        passHostHeader: true

tls:
  certificates:
    - certFile: /etc/traefik/certs/fullchain.pem
      keyFile: /etc/traefik/certs/privkey.pem
