accesslog: true
api:
  dashboard: true
  insecure: true

log:
  level: "DEBUG"

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
    #proxyProtocol:
    #  insecure: true

serversTransport:
  insecureSkipVerify: true

providers:
  docker:
    #endpoint: "unix:///var/run/docker.sock"
    endpoint: "tcp://socket-proxy:2375"
    watch: true
    exposedByDefault: false
    network: docker_ipvlan #default docker network to use for connections to all containers
  file:
    filename: /etc/traefik/config-services.yml

#certificatesResolvers:
#  letsencrypt:
#    acme:
#      email: <your-email>
#      storage: /letsencrypt/acme.json
#      httpChallenge:
#        entryPoint: http
