{
 "title": "Debhol server metrics",
 "description": "Basic overview of linux host metrics, based on node_exporter",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(node_time_seconds{job=\"$job\"},instance)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_boot_time_seconds,job)"
    }
   },
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "containergroup", "label": "containergroup", "query": { "query": "label_values(container_group)" } }
  ]
 },
 "panels": [
  {
   "title": "Host Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime | $host",
   "type": "stat",
   "description": "Time since last boot",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"$host\"} - node_boot_time_seconds{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Processors",
   "type": "stat",
   "description": "Number of processors",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$host\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "description": "Amount of memory",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "CPU Utilisation %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - avg(irate(node_cpu_seconds_total{mode=\"idle\",instance=~\"$host\"}[5m]))"
    }
   ]
  },
  {
   "title": "CPU Load 1m",
   "type": "stat",
   "description": "CPU load 1m",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Memory Use",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - node_memory_MemAvailable_bytes{instance=~\"$host\"} / node_memory_MemTotal_bytes{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "gauge",
   "description": "Used swap",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~'$host'} - node_memory_SwapFree_bytes{instance=~'$host'})"
    }
   ]
  },
  {
   "title": "Root FS Usage %",
   "type": "gauge",
   "description": "Root FS Usage %",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - (node_filesystem_free_bytes{mountpoint=\"/\",instance=~\"$host\"}/node_filesystem_size_bytes{mountpoint=\"/\",instance=~\"$host\"} * 100)"
    }
   ]
  },
  {
   "title": "CPU Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Load | $host",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
     "repeat": "host",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (mode) (irate(node_cpu_seconds_total{instance=~\"$host\"}[5m]))",
       "legendFormat": "{{mode}}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(rate(process_cpu_seconds_total[$interval])) * 100",
       "legendFormat": "CPU Utilization %"
      }
     ]
    },
    {
     "title": "Load",
     "type": "graph",
     "gridPos": { "h": 7, "w": 7, "x": 8, "y": 28 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "node_load1{instance=~\"$host\"} / on() group_right() count by(job, instance)(count by(job, instance, cpu)(node_cpu_seconds_total{instance=~\"$host\"}))"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory | $host",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
     "repeat": "host",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemFree_bytes{instance=~\"$host\"} > 0",
       "legendFormat": "Free"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$host\"} > 0",
       "legendFormat": "Total"
      },
      {
       "expr": "node_memory_MemAvailable_bytes{instance=~\"$host\"} > 0",
       "legendFormat": "Available"
      }
     ]
    },
    {
     "title": "Memory Usage per Container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_rss{name=~\".+\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Memory Swap per Container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_swap{name=~\".+\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Network Traffic | $host",
     "type": "graph",
     "gridPos": { "h": 6, "w": 15, "x": 0, "y": 24 },
     "repeat": "host",
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{instance=~\"$host\",device=~\"(?i)^(ens|eth).+$\"}[5m])  > 0",
       "legendFormat": "IN ({{device}})"
      },
      {
       "expr": "- irate(node_network_transmit_bytes_total{instance=~\"$host\",device=~\"(?i)^(ens|eth).+$\"}[5m]) < 0",
       "legendFormat": "OUT ({{device}})"
      }
     ]
    },
    {
     "title": "Network Traffic | $host",
     "type": "graph",
     "gridPos": { "h": 6, "w": 9, "x": 15, "y": 24 },
     "repeat": "host",
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_errs_total{instance=~\"$host\",device=~\"(?i)^(ens|eth).+$\"}[5m]) + irate(node_network_receive_drop_total{instance=~\"$host\",device=~\"(?i)^(ens|eth).+$\"}[5m])",
       "legendFormat": "Err/Drop IN ({{device}})"
      },
      {
       "expr": "- (irate(node_network_transmit_errs_total{instance=~\"$host\",device=~\"(?i)^(ens|eth).+$\"}[5m]) + irate(node_network_transmit_drop_total{instance=~\"$host\",device=~\"(?i)^(ens|eth).+$\"}[5m]))",
       "legendFormat": "Err/Drop OUT ({{device}})"
      }
     ]
    },
    {
     "title": "Sum Containers Network Traffic",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 9, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{id=\"/\"}[$interval])) by (id)",
       "legendFormat": "RECEIVED"
      },
      {
       "expr": "- sum(rate(container_network_transmit_bytes_total{id=\"/\"}[$interval])) by (id)",
       "legendFormat": "SENT"
      }
     ]
    },
    {
     "title": "Network traffic per container",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 15, "x": 9, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{name=~\".+\"}[$interval])) by (name)",
       "legendFormat": "IN {{name}}"
      },
      {
       "expr": "- rate(container_network_transmit_bytes_total{name=~\".+\"}[$interval])",
       "legendFormat": "OUT {{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Details | $host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Disk (Used%) | $host",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 25 },
     "repeat": "host",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 - (node_filesystem_avail_bytes{instance=~\"$host\",fstype!~\"(tmpfs|rootfs)\"}/node_filesystem_size_bytes{instance=~\"$host\",fstype!~\"(tmpfs|rootfs)\"} * 100)",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Disk I/O $host",
     "type": "graph",
     "description": "READ/WRITE bytes",
     "gridPos": { "h": 10, "w": 8, "x": 9, "y": 25 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "-sum(rate(node_disk_read_bytes_total[$interval])) by (device)",
       "legendFormat": "READ on /{{device}}"
      },
      {
       "expr": "sum(rate(node_disk_written_bytes_total[$interval])) by (device)",
       "legendFormat": "WRITE on /{{device}}"
      }
     ]
    },
    {
     "title": "Disk IO | $host",
     "type": "graph",
     "description": "Read time in seconds based on 5m intervals",
     "gridPos": { "h": 7, "w": 7, "x": 17, "y": 25 },
     "repeat": "host",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "- irate(node_disk_read_time_seconds_total{instance=~\"$host\"}[5m]) < 0",
       "legendFormat": "Read ({{device}})"
      },
      {
       "expr": "irate(node_disk_write_time_seconds_total{instance=~\"$host\"}[5m]) > 0",
       "legendFormat": "Write ({{device}})"
      }
     ]
    },
    {
     "title": "Disk (Free)",
     "type": "table-old",
     "gridPos": { "h": 10, "w": 9, "x": 0, "y": 32 },
     "repeat": "host",
     "targets": [
      {
       "expr": "node_filesystem_free_bytes{fstype!~\"(tmpfs|rootfs).*\",instance=~\"$host\"}"
      }
     ]
    },
    {
     "title": "Disk Activity | $host",
     "type": "graph",
     "description": "Rate samples based on 5m intervals",
     "gridPos": { "h": 8, "w": 8, "x": 9, "y": 35 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "-irate(node_disk_read_bytes_total{instance=~\"$host\"}[5m]) < 0",
       "legendFormat": "Read ({{device}})"
      },
      {
       "expr": "irate(node_disk_written_bytes_total{instance=~\"$host\"}[5m]) > 0",
       "legendFormat": "Write ({{device}})"
      }
     ]
    }
   ]
  }
 ]
}