{
 "title": "Sensors",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "temperature C",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time(rpi_temperature{group=\"sensors\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "humidity %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "avg_over_time(rpi_humidity[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CO2 ppm",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg_over_time(rpi_co2[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}