{
 "title": "Linux Hosts Metrics22 Copy",
 "description": "Basic overview of linux host metrics, based on node_exporter",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(node_time_seconds{job=\"$job\"},instance)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_boot_time_seconds,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Host Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Uptime | $host",
     "type": "stat",
     "description": "Time since last boot",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
     "repeat": "host",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "node_time_seconds{instance=~\"$host\"} - node_boot_time_seconds{instance=~\"$host\"}"
      }
     ]
    },
    {
     "title": "Processors",
     "type": "stat",
     "description": "Number of processors",
     "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
     "repeat": "host",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count(count(node_cpu_seconds_total{instance=~\"$host\"}) by (cpu))"
      }
     ]
    },
    {
     "title": "RAM",
     "type": "stat",
     "description": "Amount of memory",
     "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
     "repeat": "host",
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$host\"}"
      }
     ]
    },
    {
     "title": "CPU Load",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
     "repeat": "host",
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "1 - avg(irate(node_cpu_seconds_total{mode=\"idle\",instance=~\"$host\"}[5m]))"
      }
     ]
    },
    {
     "title": "Memory Use",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
     "repeat": "host",
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "1 - node_memory_MemAvailable_bytes{instance=~\"$host\"} / node_memory_MemTotal_bytes{instance=~\"$host\"}"
      }
     ]
    },
    {
     "title": "Disk Free (Total)",
     "type": "gauge",
     "description": "Free diskspace",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
     "repeat": "host",
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "1 - (sum(node_filesystem_free_bytes{instance=~\"$host\"}) / sum(node_filesystem_size_bytes{instance=~\"$host\"}))"
      }
     ]
    },
    {
     "title": "Net IN (24h)",
     "type": "stat",
     "description": "Network traffic in the last hour",
     "gridPos": { "h": 4, "w": 2, "x": 15, "y": 1 },
     "repeat": "host",
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(increase(node_network_receive_bytes_total{instance=~\"$host\"}[24h]))"
      }
     ]
    },
    {
     "title": "Net OUT (24h)",
     "type": "stat",
     "description": "Network traffic in the last hour",
     "gridPos": { "h": 4, "w": 2, "x": 17, "y": 1 },
     "repeat": "host",
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(increase(node_network_transmit_bytes_total{instance=~\"$host\"}[24h]))"
      }
     ]
    },
    {
     "title": "Disk (Free)",
     "type": "table-old",
     "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
     "repeat": "host",
     "targets": [
      {
       "expr": "node_filesystem_free_bytes{fstype!~\"(tmpfs|rootfs).*\",instance=~\"$host\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Load | $host",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
     "repeat": "host",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (mode) (irate(node_cpu_seconds_total{instance=~\"$host\"}[5m]))",
       "legendFormat": "{{mode}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory | $host",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
     "repeat": "host",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemFree_bytes{instance=~\"$host\"} > 0",
       "legendFormat": "Free"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$host\"} > 0",
       "legendFormat": "Total"
      },
      {
       "expr": "node_memory_MemAvailable_bytes{instance=~\"$host\"} > 0",
       "legendFormat": "Available"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Network Traffic | $host",
     "type": "graph",
     "gridPos": { "h": 6, "w": 14, "x": 0, "y": 4 },
     "repeat": "host",
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{instance=~\"$host\",device=~\"(?i)^(ens|eth).+$\"}[5m])  > 0",
       "legendFormat": "IN ({{device}})"
      },
      {
       "expr": "- irate(node_network_transmit_bytes_total{instance=~\"$host\",device=~\"(?i)^(ens|eth).+$\"}[5m]) < 0",
       "legendFormat": "OUT ({{device}})"
      }
     ]
    },
    {
     "title": "Network Traffic | $host",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 4 },
     "repeat": "host",
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_errs_total{instance=~\"$host\",device=~\"(?i)^(ens|eth).+$\"}[5m]) + irate(node_network_receive_drop_total{instance=~\"$host\",device=~\"(?i)^(ens|eth).+$\"}[5m])",
       "legendFormat": "Err/Drop IN ({{device}})"
      },
      {
       "expr": "- (irate(node_network_transmit_errs_total{instance=~\"$host\",device=~\"(?i)^(ens|eth).+$\"}[5m]) + irate(node_network_transmit_drop_total{instance=~\"$host\",device=~\"(?i)^(ens|eth).+$\"}[5m]))",
       "legendFormat": "Err/Drop OUT ({{device}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Details | $host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Disk (Used%) | $host",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 25 },
     "repeat": "host",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 - (node_filesystem_avail_bytes{instance=~\"$host\",fstype!~\"(tmpfs|rootfs)\"}/node_filesystem_size_bytes{instance=~\"$host\",fstype!~\"(tmpfs|rootfs)\"} * 100)",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Disk Activity | $host",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 9, "y": 25 },
     "repeat": "host",
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{instance=~\"$host\"}[5m]) > 0",
       "legendFormat": "Read ({{device}})"
      },
      {
       "expr": "- irate(node_disk_written_bytes_total{instance=~\"$host\"}[5m]) < 0",
       "legendFormat": "Write ({{device}})"
      }
     ]
    },
    {
     "title": "Disk IO | $host",
     "type": "graph",
     "gridPos": { "h": 7, "w": 7, "x": 17, "y": 25 },
     "repeat": "host",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_read_time_seconds_total{instance=~\"$host\"}[5m]) > 0",
       "legendFormat": "Read ({{device}})"
      },
      {
       "expr": "- irate(node_disk_write_time_seconds_total{instance=~\"$host\"}[5m]) < 0",
       "legendFormat": "Write ({{device}})"
      }
     ]
    }
   ]
  }
 ]
}