name: "samba" #Compose project name.
services:
  smb:        #container name
    image: smb:latest
    build:
       context: .
       args:
         SMB_PASS: ${SMB_PASS}
    restart: always
    volumes:
      - /infra/git/infra_as_code/Docker_projects/samba:/config
      - /data/ol_storage/HDD400:/shared1
      - /srv:/shared2
    networks:
      docker_ipvlan:
        ipv4_address: 10.1.0.20
networks:
  docker_ipvlan:
    driver: ipvlan
    name: docker_ipvlan
    external: true
