[global]
   security = user
   map to guest = Bad User

[shared]
path = /shared
   browseable = yes
   read only = no
   create mask = 666
   directory mask = 777
   guest ok = yes
   force user = nobody
