[global]
   security = user
   map to guest = Bad User

[HDD400]
  path = /shared1
  comment = Ol Storage files
  browseable = yes
  read only = no
  create mask = 666
  directory mask = 777
  guest ok = yes
  force user = nobody
[HDD400s]
   path = /shared1
  comment = Ol Storage files with 'guest' username
   browsable = yes
   writable = yes
   valid users = guest
   read only = no
   create mask = 0660
   directory mask = 0777
[Test_share]
  path = /shared2
  comment = Some other test share
  browseable = yes
  read only = no
  create mask = 666
  directory mask = 777
  guest ok = yes
  force user = nobody
